### ISSUE TITLE
Segfault when XDG_RUNTIME_DIR is not specified.

### ISSUE THREAD

**Issue by elderK** [ttygde/pokoy#10] opened 2017-07-11 04:41 UTC
Hey there,

I just thought I'd let you know that Pokoy segfaults when the XDG_RUNTIME_DIR environment variable is not set.

**Comment by matmatyk** [comment] 2020-05-10 16:36
Can't reproduce on current master (v0.2.3). Probably fixed in dc50a5749cba0311002791f9ede3e99dfdfdc52c. Closing.

**Closed by matmatyk** 2020-05-10 16:36 UTC
Labels: bug, good first issue
